dist: trusty
sudo: require
language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=True
    - cmake --build .
    - ctest
after_success:
  - bash <(curl -s https://codecov.io/bash) -v
  - coveralls --verbose -E .+/stb_.+
