# version string format
version: "{build}"

image:
    - Visual Studio 2019
    - Ubuntu2004

init:
    - git config --global core.autocrlf input

# branches to build
branches:
    # whitelist
    only:
        - master

platform:
    - x86
    - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
    - Debug
    - Release

#environment:
#  matrix:

#  - job_name: Windows build
#    appveyor_build_worker_image: Visual Studio 2019

#  - job_name: Linux build
#    appveyor_build_worker_image: Ubuntu2004

matrix:
  fast_finish: true

# job-specific configurations
for:

  -
    matrix:
      only:
        #- job_name: Windows build
        - image: Visual Studio 2019

    clone_folder: C:\projects\nkar

    build_script:
    - cmd: echo This is Windows-specific build script
    - cmd: cd C:\projects\nkar
    - cmd: mkdir build && cd build
    - cmd: cmake .. -DENABLE_TESTING=True
    - cmd: cmake --build . --config=Release

    test_script:
    - cd C:\projects\nkar\build
    - ctest -C Release

  -
    matrix:
      only:
        #- job_name: Linux build
        - image: Ubuntu2004

    clone_folder: /home/appveyor/projects/nkar

    install:
        - sudo apt-get install gcc-multilib g++-multilib -y

    build_script:
    - sh: echo Linux build x86 \(Release\)
    - sh: cd /home/appveyor/projects/nkar
    - sh: mkdir build && cd build
    - sh: cmake .. -DTARGET_ARCH=x86 -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=True
    - sh: make

    test_script:
    - cd /home/appveyor/projects/nkar/build
    - ctest

    after_test:
    - sh: cpack

    artifacts:
    - path: '**\*.tar.gz'
